// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjBhDeTHgiBWVmKRNqYcgpF0cYXashf7I',
    appId: '1:44138888808:web:493402dd91b3e1be4f05dd',
    messagingSenderId: '44138888808',
    projectId: 'sample-app-c2eef',
    authDomain: 'sample-app-c2eef.firebaseapp.com',
    storageBucket: 'sample-app-c2eef.appspot.com',
    measurementId: 'G-W6VML372RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi_ECsnK9PCvH-z2PMgKSCNKXYIG9zl4o',
    appId: '1:44138888808:android:4b134137fa4aac1f4f05dd',
    messagingSenderId: '44138888808',
    projectId: 'sample-app-c2eef',
    storageBucket: 'sample-app-c2eef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5DyehLqKCTPsoC25Ql6FJmpz1S7tWsko',
    appId: '1:44138888808:ios:b5bad49e77cb5be94f05dd',
    messagingSenderId: '44138888808',
    projectId: 'sample-app-c2eef',
    storageBucket: 'sample-app-c2eef.appspot.com',
    iosBundleId: 'com.example.solutionSoulInterviewTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5DyehLqKCTPsoC25Ql6FJmpz1S7tWsko',
    appId: '1:44138888808:ios:35f5378e4d11b20e4f05dd',
    messagingSenderId: '44138888808',
    projectId: 'sample-app-c2eef',
    storageBucket: 'sample-app-c2eef.appspot.com',
    iosBundleId: 'com.example.solutionSoulInterviewTest.RunnerTests',
  );
}
